Supporting template evaluation in ingress hosts
dexidp/helm-charts pull request #104
Opened 2023-01-30 15:00 UTC by jkroepke

Signed-off-by: Jan-Otto Kröpke <github@jkroepke.de>

#### Overview

Hi, I would like to use dex as part of a umbrella helm chart. For the user experience, there one global domain configuration across all helm charts and sub-charts are able to use the helm evaluation function to build a hostname. After merging the PR, I could use somelike like this in my value yaml

```yaml
dex:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: 'auth.{{ $.Values.global.domain }}'
      paths:
      - path: /
         pathType: Prefix
    tls:
    - secretName: tls-secret-dex
      hosts:
      - 'auth.{{ $.Values.global.domain }}'
```

And user only needs to define `--set global.domain=example.com`.

Note, w/o this, end users needs to pass the whole list item, since helm is not able to merge lists.

#### What this PR does / why we need it

#### Special notes for your reviewer

[kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/c3b697d31b8631fb8847f7f313155deeb5962f98/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml#L33) and grafana helm chart are supporting this scenario, too

#### Checklist

- [ ] Change log updated in `Chart.yaml` (see the contributing guide for details)
- [ ] Chart version bumped in `Chart.yaml` (see the contributing guide for details)
- [ ] Documentation regenerated by running `make docs`

2023-02-06 14:40 UTC, jkroepke commented
@sagikazarmark I'm aware pinging maintainers is not such a good thing! I would highly appreciate some feedback here.

2023-02-06 18:25 UTC, sagikazarmark commented
@jkroepke I maintain dozens, if not hundreds of projects (which means I get at least a hundred emails from GitHub daily). Pinging me is the ONLY way to get my attention. Don't feel bad about that (but also don't take it personally if I don't answer for a long time).

I'm generally not a huge fan of this pattern, but it's a small change, low maintenance and may actually be more popular than I would have thought (didn't know prometheus uses this pattern), so I think it's okay to add.

2023-02-06 18:26 UTC, sagikazarmark requested changes
Please run `make docs`

2023-02-06 19:15 UTC, jkroepke commented
Thanks @sagikazarmark, I additionally run `make docs`

2023-02-11 13:22 UTC, jkroepke commented
@sagikazarmark are the actions failures related to this change?

2023-02-20 08:19 UTC, jkroepke commented
@sagikazarmark is there anything what I can do to unblock this here?

2023-03-04 16:01 UTC, jkroepke commented
@sagikazarmark how we can procceed here? Removing old kubernetes versions may be the best option here. (1.19+ is green)

2023-04-05 13:25 UTC, sagikazarmark commented
Can you please rebase @jkroepke ?

2023-04-05 20:25 UTC, jkroepke commented
@sagikazarmark rebased

2023-04-06 05:54 UTC, sagikazarmark approved these changes

2023-04-06 07:54 UTC, merged