feat: add external secret support
dexidp/helm-charts pull request #33
Opened 2021-04-30 18:27 UTC by eddycharly

This PR adds external secret support.

This is useful to let the end user bring his own configuration from an existing secret.

2021-04-30 22:35 UTC, sagikazarmark requested changes
Thanks @edddycharly for the contribution! I had a few comments, can you please take a look at them?

2021-04-30 22:35 UTC, sagikazarmark commented on charts/dex/Chart.yaml
> +version: 0.2.1
Since this is a new feature, please bump the minor versiom.

2021-04-30 22:35 UTC, sagikazarmark commented on charts/dex/templates/secret.yaml
> +{{ end }}
Please adhere .editorconfig settings.

2021-04-30 22:35 UTC, sagikazarmark commented on charts/dex/values.yaml
> +  name: ''
I think I'd prefer something like the `serviceAccount` here:

```suggestion
configSecret:
  # -- Enable creating a secret from the values passed to `config`.
  # If set to false, name must point to an existing secret.
  create: true

  # -- The name of the secret to mount as configuration in the pod.
  # If not set and create is true, a name is generated using the fullname template.
  # Must point to secret that contains at least a `config.yaml` key.
  name: ""
```

2021-04-30 22:35 UTC, sagikazarmark commented on charts/dex/templates/deployment.yaml
> +            secretName: {{ if .Values.useExternalSecret.enabled }}{{ .Values.useExternalSecret.name }}{{ else }}{{ include "dex.fullname" . }}{{ end }}
Can you please add a template to the end of the helpers file similar to the service account name template, based on the comments in the values file?

2021-04-30 22:47 UTC, eddycharly commented
@sagikazarmark thanks for your feedback !
I addressed your comments, not sure why the CI was red though.

2021-05-01 11:38 UTC, eddycharly commented
Ah, i think I have to use the template in the secret name too

2021-05-01 11:43 UTC, eddycharly commented
The condition for creating the secret was wrong, fixed.

2021-05-01 12:12 UTC, sagikazarmark approved these changes

2021-05-01 12:14 UTC, sagikazarmark commented
@eddycharly yeah, I think adding a test for that would make sense. You can add a `ci/config-secret-values.yaml` file with the following content:

```yaml
configSecret:
  name: my-super-special-dex-secret
```

That should ensure that the custom template is used everywhere and prevent us from introducing a regression.

2021-05-01 12:19 UTC, eddycharly commented
@sagikazarmark I added the ci test file.

2021-05-01 14:10 UTC, sagikazarmark commented
Thanks @eddycharly!

2021-05-01 14:10 UTC, sagikazarmark approved these changes

2021-05-01 14:11 UTC, merged